version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "12:00"
    commit-message:
      prefix: "DEPENDABOT: "