FROM oven/bun:1-alpine

WORKDIR /app

COPY . .

ARG PORT=8080
ARG DATABASE
ARG DATABASE_HOST
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG TG_BOT_TOKEN
ARG BITRIX_URL

ENV PORT=$PORT DATABASE=$DATABASE DATABASE_HOST=$DATABASE_HOST DATABASE_USER=$DATABASE_USER DATABASE_PASSWORD=$DATABASE_PASSWORD TG_BOT_TOKEN=$TG_BOT_TOKEN BITRIX_URL=$BITRIX_URL

RUN bun install --frozen-lockfile --production

RUN bun run build

EXPOSE 8080

CMD bun migrate:latest:production && bun run start
