version: "0.1"
services:
  backend:
    build: .
    ports:
      - 8080:8080
    env_file: .env.production
    depends_on:
      - database
  database:
    image: postgres:14.2
    environment:
      POSTGRES_USER: rdga_admin
      POSTGRES_PASSWORD: lol_u_believed
      POSTGRES_DB: rdga_db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data:
