@hostname = localhost
@port = 8080
@protocol = http
@host = {{protocol}}://{{hostname}}:{{port}}

### Get all players
GET {{host}}/players?pageNumber=1&surname=test&town=Нижний Новгород

### Get player by RDGA number
GET {{host}}/players/1

### Create player
POST {{host}}/players
Content-Type: application/json

{
  "name": "Гарри",
  "surname": "Поттер",
  "rdgaNumber": 1,
  "rdgaRating": 1000,
  "rdgaRatingChange": 0,
  "town": "Годрикова Впадина",
  "email": "harry-potter@hogwarts.com",
  "pdgaNumber": 1,
  "metrixNumber": 1,
  "priority": 0
}

### Update player
PUT {{host}}/players/1
Content-Type: application/json

{
  "name": "Гарри",
  "surname": "Поттер",
  "rdgaRating": 1000,
  "rdgaRatingChange": 0,
  "town": "Годрикова Впадина",
  "email": "harry-potter@muggle.com",
  "pdgaNumber": 1,
  "metrixNumber": 1,
  "priority": 1
}

### Delete player

DELETE {{host}}/players/1

### Update player rating
PATCH {{host}}/players/1/rdgaRating
Content-Type: application/json

{
  "rating": 1000
}
