name: Build+Push Docker Image

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKER_LOGIN:
        required: true
      DOCKER_PASSWORD:
        required: true
      BACKEND_PORT:
        required: true
      DATABASE:
        required: true
      DATABASE_HOST:
        required: true
      DATABASE_USER:
        required: true
      DATABASE_PASSWORD:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cherkasik/rdga-backend:latest
          build-args:
            PORT=${{ secrets.BACKEND_PORT }},
            DATABASE=${{ secrets.DATABASE }},
            DATABASE_HOST=${{ secrets.DATABASE_HOST }},
            DATABASE_USER=${{ secrets.DATABASE_USER }},
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
