name: Check Code Quality

on:
  push

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      -
        name: Install dependencies
        run: yarn install
      -
        name: Check ESLint
        run: yarn eslint:check
      -
        name: Check Types
        run: yarn types:check
      -
        name: Start database for tests
        run: yarn database:start
      -
        name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v8
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test:coverage
          debug: true
      -
        name: Stop database
        run: yarn database:stop
