name: Update Docker and Deploy (Production)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-docker:
    uses: RDGAapp/backend/.github/workflows/build-push.yml@main
    secrets:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      DATABASE: ${{ secrets.DATABASE }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  deploy:
    needs: update-docker
    uses: RDGAapp/docker-compose/.github/workflows/update.yml@main
    secrets:
      VDS_HOST: ${{ secrets.VDS_HOST }}
      VDS_USER: ${{ secrets.VDS_USER }}
      VDS_PASSWORD: ${{ secrets.VDS_PASSWORD }}
      VDS_PORT: ${{ secrets.VDS_PORT }}
